"""Verifier gates for model-proposed symbolic hypotheses (Phase 6)."""
from fractions import Fraction

from faultline_core import (
    FractionProblem,
    HYPOTHESIS_MAP,
    SynthesisExample,
    verify_symbolic_hypothesis,
)

ADD_ACROSS = {
    "op": "fraction",
    "args": [
        {"op": "add", "args": [{"var": "n1"}, {"var": "n2"}]},
        {"op": "add", "args": [{"var": "d1"}, {"var": "d2"}]},
    ],
}

# A genuinely novel-but-safe procedure not in the known library:
# add numerators, multiply denominators.
NOVEL = {
    "op": "fraction",
    "args": [
        {"op": "add", "args": [{"var": "n1"}, {"var": "n2"}]},
        {"op": "mul", "args": [{"var": "d1"}, {"var": "d2"}]},
    ],
}


def _problems() -> list[FractionProblem]:
    return [
        FractionProblem("p1", 1, 2, 1, 3),
        FractionProblem("p2", 2, 3, 1, 4),
        FractionProblem("p3", 3, 5, 1, 2),
        FractionProblem("p4", 1, 4, 2, 3),
        FractionProblem("p5", 2, 5, 1, 3),
        FractionProblem("p6", 3, 8, 1, 6),
    ]


def _examples_from(expression) -> list[SynthesisExample]:
    from faultline_core import evaluate

    return [
        SynthesisExample(p, evaluate(expression, {"n1": p.n1, "d1": p.d1, "n2": p.n2, "d2": p.d2}))
        for p in _problems()
    ]


def test_valid_novel_proposal_accepted() -> None:
    result = verify_symbolic_hypothesis("add tops, multiply bottoms", NOVEL, _examples_from(NOVEL))
    assert result.accepted is True
    assert result.reproduction == 1.0
    assert result.label == "provisional_verified_symbolic_hypothesis"
    assert result.novelty_signature is not None


def test_duplicate_of_known_rule_rejected() -> None:
    result = verify_symbolic_hypothesis("adds across", ADD_ACROSS, _examples_from(ADD_ACROSS))
    assert result.accepted is False
    assert result.reason.startswith("duplicate_of_known:add_across")


def test_insufficient_fit_rejected() -> None:
    # Fit examples generated by add_across, but proposal is the novel rule → poor fit.
    add_examples = [
        SynthesisExample(p, HYPOTHESIS_MAP["add_across"].predict(p)) for p in _problems()
    ]
    result = verify_symbolic_hypothesis("mismatch", NOVEL, add_examples)
    assert result.accepted is False
    assert result.reason == "insufficient_fit"


def test_validation_failure_rejected() -> None:
    fit = _examples_from(NOVEL)
    # Held-out validation labelled with a different (correct) procedure → fails.
    validation = [
        SynthesisExample(p, HYPOTHESIS_MAP["correct_common_denominator"].predict(p))
        for p in _problems()
    ]
    result = verify_symbolic_hypothesis("novel", NOVEL, fit, validation)
    assert result.accepted is False
    assert result.reason == "insufficient_validation"


def test_invalid_dsl_rejected() -> None:
    bad = {"op": "exec", "args": [1, 2]}
    result = verify_symbolic_hypothesis("code", bad, _examples_from(NOVEL))
    assert result.accepted is False
    assert result.reason.startswith("invalid_dsl")


def test_string_logic_rejected() -> None:
    bad = {"op": "add", "args": ["n1", "n2"]}  # strings are not valid DSL nodes
    result = verify_symbolic_hypothesis("strings", bad, _examples_from(NOVEL))
    assert result.accepted is False
    assert result.reason.startswith("invalid_dsl")


def test_excessive_complexity_rejected() -> None:
    node: object = {"var": "n1"}
    for _ in range(15):
        node = {"op": "add", "args": [node, 1]}
    expression = {"op": "fraction", "args": [node, {"var": "d1"}]}
    examples = _examples_from(NOVEL)  # content irrelevant; complexity gate fires first-ish
    result = verify_symbolic_hypothesis("deep", expression, examples)
    assert result.accepted is False
    assert result.reason in {"too_complex", "invalid_dsl:expression is too complex"} or result.reason.startswith("invalid_dsl")


def test_no_item_ids_possible() -> None:
    # There is no DSL construct to reference an item id or observed answer, so a
    # proposal cannot memorize. A dict that tries is simply an invalid node.
    bad = {"op": "add", "args": [{"item": "p1"}, {"var": "n1"}]}
    result = verify_symbolic_hypothesis("memorize", bad, _examples_from(NOVEL))
    assert result.accepted is False
    assert result.reason.startswith("invalid_dsl")


def test_deterministic_repeated_outcome() -> None:
    a = verify_symbolic_hypothesis("novel", NOVEL, _examples_from(NOVEL))
    b = verify_symbolic_hypothesis("novel", NOVEL, _examples_from(NOVEL))
    assert a.accepted == b.accepted
    assert a.novelty_signature == b.novelty_signature
